spring.application.name=jira-app
spring.datasource.url=jdbc:postgresql://localhost:5432/kanban
spring.datasource.username=postgres
spring.datasource.password=saurav
spring.jpa.hibernate.ddl-auto=update
